### ISSUE TITLE
Invalid plantuml files generated with multiline edn contents

### ISSUE THREAD

**Issue by tobias-hammerschmidt** [soulspace-org/overarch#19]
I tried to use multi-line strings which are supported in the edn format (https://github.com/edn-format/edn?tab=readme-ov-file#strings) for the :desc value of some model elements. However plantuml files created by overarch (0.18.0) for these models can not be converted into images due to some parse error.

**Comment by lsolbach** [comment]
Fixed. It will be included in the next release.
