### ISSUE TITLE
Feature Request: warn/error about nonexisting "rel-element" referenced in views.

### ISSUE THREAD

**Issue by gmuth** [soulspace-org/overarch#5]
Currently you don't get any feedback, when a referenced rel does not exists - it just doesn't show up in the view.
In order the keep the quality of the model and views we really should get as much feedback as possible when something is inconsistent (without having to enable extra options).

**Comment by lsolbach** [comment]
Better feedback is on the agenda and will be implemented for the next release. Checks will probably implemented as a separate validation stage as I don't really want to mess with error handling in the transformation pipelines. But that does not imply some separate options.

**Comment by lsolbach** [comment]
Reporting is enabled per default in release 0.9.0.
